import React, { useState } from 'react';
import { 
  ArrowLeft, X, Download, Copy, Check, ShieldAlert, 
  ExternalLink, Mail, Shield, CheckCircle2, FileText
} from 'lucide-react';

export default function DossierViewerModal({ dossier, onClose }) {
  const [copied, setCopied] = useState(false);
  const [downloaded, setDownloaded] = useState(false);

  if (!dossier) return null;

  const {
    refId = `I4C-${Date.now()}`,
    timestamp = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }),
    type = 'UPI Financial Extortion',
    target = 'scammer.cybercell@oksbi',
    amount = 'N/A',
    riskScore = 98,
    isBlocked = true,
    summary = 'Flagged in National Cybercrime Registry (I4C / 1930 Helpline)',
    transcript = '',
    safetyAdvice = 'Do not transfer funds. Official police never demand online payments.'
  } = dossier;

  const fullReportText = `=====================================================
NATIONAL CYBERCRIME REPORTING PORTAL (HELPLINE 1930)
EVIDENCE DOSSIER - GENERATED BY VERIX SENTINEL
=====================================================
Incident Reference ID : ${refId}
Detection Timestamp   : ${timestamp} IST
Incident Type         : ${type}
Flagged Target / VPA  : ${target}
Intercepted Amount    : ${amount}
Threat Risk Score     : ${riskScore} / 100 (${isBlocked ? 'CRITICAL BLOCKED' : 'HIGH RISK'})
Firewall Status       : PRE-TRANSACTION FIREWALL BLOCKED

EVIDENCE SUMMARY:
${summary}

${transcript ? `COERCIVE MESSAGE / TRANSCRIPT:\n"${transcript}"\n` : ''}
OFFICIAL 1930 REPORTING INSTRUCTIONS:
1. Dial 1930 immediately to register financial fraud complaint.
2. File an official cyber report at https://cybercrime.gov.in referencing Dossier ID: ${refId}.
3. Verix has prevented account debit. Do not attempt payment using unverified apps.

Generated by Verix Real-Time Cyber Fraud Defense Protocol. Digitally hash-verified.`;

  const handleDownloadFile = () => {
    try {
      const blob = new Blob([fullReportText], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `Verix_1930_Incident_Dossier_${refId}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      setDownloaded(true);
      setTimeout(() => setDownloaded(false), 2500);
    } catch (e) {
      console.warn('[Download Dossier Error]:', e);
    }
  };

  const handleCopyText = () => {
    try {
      navigator.clipboard?.writeText(fullReportText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch (e) {}
  };

  const handleEmail1930 = () => {
    const subject = encodeURIComponent(`[URGENT 1930 FINANCIAL FRAUD DOSSIER ${refId}] Target: ${target}`);
    const body = encodeURIComponent(fullReportText);
    window.open(`mailto:cybercrime@gov.in,1930helpdesk@i4c.gov.in?subject=${subject}&body=${body}`, '_blank');
  };

  return (
    <div className="fixed inset-0 max-w-[480px] mx-auto z-50 bg-black/95 text-[#F2F2F3] flex flex-col font-sans select-none overflow-hidden animate-fade-in">
      {/* ── TOP APP BAR WITH BACK & CLOSE BUTTON ── */}
      <header className="sticky top-0 z-50 bg-[#131315] border-b border-[#2A2A2E] flex justify-between items-center w-full px-4 py-3.5 shadow-md">
        <button
          onClick={onClose}
          className="flex items-center gap-1.5 text-xs font-semibold text-[#8A8F9E] hover:text-white active:scale-95 transition-all cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4 stroke-[2.5]" /> Back to App
        </button>
        <div className="flex items-center gap-1.5">
          <Shield className="w-4 h-4 text-white" />
          <span className="font-bold text-xs text-[#F2F2F3]">1930 Evidence Dossier</span>
        </div>
        <button
          onClick={onClose}
          className="w-7 h-7 rounded-full bg-[#1D1D20] border border-[#2A2A2E] flex items-center justify-center text-[#8A8F9E] hover:text-white cursor-pointer active:scale-90"
        >
          <X className="w-4 h-4" />
        </button>
      </header>

      {/* ── MAIN SCROLLABLE DOSSIER CANVAS ── */}
      <main className="flex-1 overflow-y-auto px-4 py-4 space-y-4 pb-28">
        {/* Compliance Header Banner */}
        <div className="bg-[#131315] border border-[#2A2A2E] rounded-[20px] p-4 space-y-2.5 shadow-[inset_0_1px_0_0_rgba(255,255,255,0.06)]">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-[#8A8F9E]">
              OFFICIAL I4C REPORT
            </span>
            <span className="text-[10px] font-mono font-bold px-2 py-0.5 rounded border bg-[#FF4B4B]/10 border-[#FF4B4B]/30 text-[#FF4B4B]">
              BLOCKED EVIDENCE
            </span>
          </div>
          <h2 className="text-base font-bold text-[#F2F2F3]">National Cybercrime Dossier</h2>
          <p className="text-xs text-[#8A8F9E] font-mono">Ref ID: {refId}</p>
        </div>

        {/* Evidence Table */}
        <div className="bg-[#131315] border border-[#2A2A2E] rounded-[18px] p-4 space-y-2.5 text-xs font-mono">
          <div className="flex justify-between border-b border-[#2A2A2E] pb-2">
            <span className="text-[#8A8F9E]">Timestamp</span>
            <span className="text-[#F2F2F3]">{timestamp}</span>
          </div>
          <div className="flex justify-between border-b border-[#2A2A2E] pb-2">
            <span className="text-[#8A8F9E]">Incident Type</span>
            <span className="text-[#F2F2F3]">{type}</span>
          </div>
          <div className="flex justify-between border-b border-[#2A2A2E] pb-2">
            <span className="text-[#8A8F9E]">Flagged Handle</span>
            <span className="text-white font-bold">{target}</span>
          </div>
          <div className="flex justify-between border-b border-[#2A2A2E] pb-2">
            <span className="text-[#8A8F9E]">Amount</span>
            <span className="text-white font-bold">{amount}</span>
          </div>
          <div className="flex justify-between items-center">
            <span className="text-[#8A8F9E]">Risk Score</span>
            <span className="text-[#FF4B4B] font-bold">{riskScore}/100 (CRITICAL BLOCKED)</span>
          </div>
        </div>

        {/* Coercive Note / Transcript */}
        {transcript && (
          <div className="bg-[#131315] border border-[#2A2A2E] rounded-[18px] p-4 space-y-1.5">
            <h4 className="text-[11px] font-mono uppercase tracking-wider text-[#8A8F9E]">
              Coercive Trigger / Speech Intercept
            </h4>
            <div className="bg-[#0A0A0B] border border-[#2A2A2E] rounded-xl p-3 text-xs font-mono text-[#F2F2F3] leading-relaxed">
              "{transcript}"
            </div>
          </div>
        )}

        {/* Threat Explanation */}
        <div className="bg-[#131315] border border-[#2A2A2E] rounded-[18px] p-4 space-y-1.5">
          <h4 className="text-[11px] font-mono uppercase tracking-wider text-[#8A8F9E]">
            Threat Assessment &amp; Advice
          </h4>
          <p className="text-xs text-[#8A8F9E] leading-relaxed">
            {summary}
          </p>
        </div>
      </main>

      {/* ── FIXED BOTTOM ACTION SHEET ── */}
      <footer className="fixed bottom-0 left-0 right-0 max-w-[480px] mx-auto bg-[#131315]/95 backdrop-blur-md border-t border-[#2A2A2E] p-4 space-y-2 z-50">
        <div className="flex gap-2">
          {/* Download File Button */}
          <button
            onClick={handleDownloadFile}
            className="btn-tier-1 flex-1 py-3 text-xs font-semibold flex items-center justify-center gap-1.5 cursor-pointer"
          >
            {downloaded ? <Check className="w-4 h-4 text-black stroke-[3]" /> : <Download className="w-4 h-4 text-black" />}
            <span>{downloaded ? 'Downloaded!' : 'Download File'}</span>
          </button>

          {/* Copy Text Button */}
          <button
            onClick={handleCopyText}
            className="btn-tier-2 flex-1 py-3 text-xs font-semibold flex items-center justify-center gap-1.5 cursor-pointer"
          >
            {copied ? <Check className="w-4 h-4 text-[#3ECF7A] stroke-[3]" /> : <Copy className="w-4 h-4 text-white" />}
            <span>{copied ? 'Copied Text!' : 'Copy Text'}</span>
          </button>
        </div>

        {/* Email to 1930 / I4C */}
        <button
          onClick={handleEmail1930}
          className="btn-tier-3 w-full py-2.5 text-xs font-semibold flex items-center justify-center gap-1.5 cursor-pointer"
        >
          <Mail className="w-4 h-4 text-white" />
          <span>Email Dossier to 1930 Nodal Desk</span>
        </button>
      </footer>
    </div>
  );
}
